import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./Components/Shared/NavBar";
import Footer from "./Components/Shared/Footer.";
import ScrollProgressBar from "./Components/Shared/ScrollProgressBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900"
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="sticky  w-full z-[999] top-0 Glassmorphism">
          <ScrollProgressBar />
          <NavBar />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
